@startuml
state "Running BIOS" as RunningBIOS
state "Booting OS" as BootingOS
state "Running OS" as RunningOS
state "Shut Down" as ShutDown

[*] --> RunningBIOS
RunningBIOS --> BootingOS : power button pressed
BootingOS --> RunningOS : entered credentials [valid]
BootingOS --> Error : entered credentials [not valid]
RunningOS --> ShutDown : shutdown requested
ShutDown --> [*]
@enduml
